[tool.poetry]
name = "graft"
version = "0.1.0"
description = ""
authors = ["Matt Woolley <matt.wool@live.com.au>"]
license = "GNU GENERAL PUBLIC LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.9.0"
networkx = "^3.2.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.1"
ruff = "^0.1.6"
pylint = "^3.0.2"
autoflake = "^2.2.1"
pydocstringformatter = "^0.7.3"
vulture = "^2.10"

[tool.ruff]
line-length = 88
select = ["ALL"]
ignore = ["E203", "D203", "D213", "ANN101", "ANN102", "COM812", "ISC001"]
ignore-init-module-imports = true
show-fixes = true

[tool.autoflake]
expand-star-imports = true
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-duplicate-keys = true
remove-unused-variables = true
in-place = true

[tool.pydocstringformatter]
write = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
