from typing import Final

DEFAULT_NODE_COLOUR: Final = "#1f78b4"
DEFAULT_EDGE_COLOUR: Final = "black"
HIGHLIGHTED_NODE_COLOUR = "red"
HIGHLIGHTED_EDGE_COLOUR = "red"
INTRODUCED_EDGE_COLOUR = "orange"
